### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by HanYuCR** [NieR4ever/huhubot#3]
![image](https://github.com/user-attachments/assets/9994a0a5-7a1e-4d4c-87ac-d8fce81306c6)
试了很久一直跑不起来qwq

**Comment by NieR4ever** [comment]
很久没维护了，只能在2.15以下使用，建议使用  https://github.com/cssxsh/bilibili-helper  代替

**Comment by HanYuCR** [comment]
好吧，其实我只是想用斗鱼的推送，不过还是谢谢了
